server:
  port: 8082

spring:
  application:
    name: product-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t