server:
  port: 8081

  spring:
    profiles:
      active: native
    cloud:
      config:
        server:
          git:
            uri: https://github.com/missaSantiago/microservices-store.git
            default-label: main
            username: missaSantiago
            password: missa2270xd
            searchPaths: config-data
          bootstrap: true
        enabled: true
    application:
      name: Config-Server

security:
  user:
    name: root
    user: s3cr3t