server:
  port: 8081

  spring:
    profiles:
      active: native
    cloud:
      config:
        server:
          git:
            uri: https://github.com/missaSantiago/microservices-store.git
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
            searchPaths: config-data
          default-label: main
          bootstrap: true
        enabled: true
    application:
      name: Config-Server

security:
  user:
    name: root
    user: s3cr3t