server:
  port: 8081

  spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/missaSantiago/microservices-store.git

security:
  user:
    name: root
    user: s3cr3t